# ============================================================
# Update discharge download summaries
# Stage: 05_discharge_measurements
#
# Purpose:
# Build availability and status summaries from the discharge
# request log generated by pipeline/R/042_download_discharge_routes.R
# and pipeline/R/042_retry_failed_discharge_requests.R.
#
# Important rule:
# Request status is evaluated by window key:
# station_code + route_name + date_start + date_end.
# A window is considered successful if it ever had success == TRUE,
# even if older attempts failed before retry.
# ============================================================

# Load packages
library(dplyr)
library(readr)
library(tibble)

# ============================================================
# Paths
# ============================================================

processed_dir <- file.path("data", "processed")

request_log_file <- file.path(
  processed_dir,
  "discharge_request_log.csv"
)

availability_index_file <- file.path(
  processed_dir,
  "discharge_availability_index.csv"
)

window_status_file <- file.path(
  processed_dir,
  "discharge_download_window_status.csv"
)

route_summary_file <- file.path(
  processed_dir,
  "discharge_download_route_summary.csv"
)

station_summary_file <- file.path(
  processed_dir,
  "discharge_download_station_summary.csv"
)

station_route_summary_file <- file.path(
  processed_dir,
  "discharge_download_station_route_summary.csv"
)

station_route_download_status_file <- file.path(
  processed_dir,
  "discharge_station_route_download_status.csv"
)

station_download_status_file <- file.path(
  processed_dir,
  "discharge_station_download_status.csv"
)

# ============================================================
# Critical checks
# ============================================================

if (!file.exists(request_log_file)) {
  stop("Missing request log file: ", request_log_file)
}

# ============================================================
# Read request log
# ============================================================

request_log <- readr::read_csv(
  request_log_file,
  col_types = readr::cols(
    station_code = readr::col_character(),
    route_name = readr::col_character(),
    endpoint = readr::col_character(),
    date_start = readr::col_character(),
    date_end = readr::col_character(),
    http_status = readr::col_double(),
    api_status = readr::col_character(),
    api_code = readr::col_character(),
    api_message = readr::col_character(),
    n_items = readr::col_double(),
    success = readr::col_logical(),
    error_message = readr::col_character(),
    raw_file = readr::col_character(),
    requested_at = readr::col_character(),
    downloaded_at = readr::col_character()
  )
)

if (nrow(request_log) == 0) {
  stop("Request log is empty.")
}

# ============================================================
# Availability index at attempt level
# ============================================================

availability_index <- request_log %>%
  mutate(
    station_code = as.character(station_code),
    route_name = as.character(route_name),
    date_start = as.character(date_start),
    date_end = as.character(date_end),
    success = as.logical(success),
    n_items = as.numeric(n_items),
    has_items = !is.na(n_items) & n_items > 0
  )

readr::write_csv(availability_index, availability_index_file)

# ============================================================
# Window-level status after retries
# ============================================================

window_status <- availability_index %>%
  mutate(
    row_id = dplyr::row_number(),
    items_success = dplyr::if_else(
      success & !is.na(n_items),
      n_items,
      0
    ),
    positive_success = success & has_items
  ) %>%
  group_by(station_code, route_name, date_start, date_end) %>%
  summarise(
    endpoint = dplyr::last(endpoint),
    n_attempts = dplyr::n(),
    n_success_attempts = sum(success, na.rm = TRUE),
    n_failed_attempts = sum(!success, na.rm = TRUE),
    ever_success = any(success, na.rm = TRUE),
    last_success = success[which.max(row_id)],
    has_items_any_success = any(positive_success, na.rm = TRUE),
    total_items_success = sum(items_success, na.rm = TRUE),
    max_items_success = suppressWarnings(max(items_success, na.rm = TRUE)),
    first_requested_at = suppressWarnings(min(requested_at, na.rm = TRUE)),
    last_downloaded_at = downloaded_at[which.max(row_id)],
    last_http_status = http_status[which.max(row_id)],
    last_error_message = error_message[which.max(row_id)],
    last_raw_file = raw_file[which.max(row_id)],
    .groups = "drop"
  ) %>%
  mutate(
    max_items_success = dplyr::if_else(
      is.infinite(max_items_success),
      NA_real_,
      max_items_success
    ),
    window_download_status = dplyr::case_when(
      ever_success ~ "completed",
      !ever_success ~ "failed",
      TRUE ~ "unknown"
    )
  )

readr::write_csv(window_status, window_status_file)

# ============================================================
# Route-level summary
# ============================================================

route_summary <- window_status %>%
  group_by(route_name) %>%
  summarise(
    n_windows = n(),
    n_success_windows = sum(ever_success, na.rm = TRUE),
    n_failed_windows = sum(!ever_success, na.rm = TRUE),
    n_attempts = sum(n_attempts, na.rm = TRUE),
    n_success_attempts = sum(n_success_attempts, na.rm = TRUE),
    n_failed_attempts = sum(n_failed_attempts, na.rm = TRUE),
    n_positive_windows = sum(has_items_any_success, na.rm = TRUE),
    total_items_success = sum(total_items_success, na.rm = TRUE),
    n_stations = dplyr::n_distinct(station_code),
    n_stations_with_failed_windows = dplyr::n_distinct(station_code[!ever_success]),
    route_download_status = dplyr::case_when(
      n_failed_windows == 0 ~ "completed",
      n_success_windows > 0 ~ "partial",
      TRUE ~ "failed"
    ),
    .groups = "drop"
  )

# ============================================================
# Station-route summary and status
# ============================================================

station_route_summary <- window_status %>%
  group_by(station_code, route_name) %>%
  summarise(
    n_windows = n(),
    n_success_windows = sum(ever_success, na.rm = TRUE),
    n_failed_windows = sum(!ever_success, na.rm = TRUE),
    n_attempts = sum(n_attempts, na.rm = TRUE),
    n_success_attempts = sum(n_success_attempts, na.rm = TRUE),
    n_failed_attempts = sum(n_failed_attempts, na.rm = TRUE),
    n_positive_windows = sum(has_items_any_success, na.rm = TRUE),
    total_items_success = sum(total_items_success, na.rm = TRUE),
    first_date_start = suppressWarnings(min(date_start, na.rm = TRUE)),
    last_date_end = suppressWarnings(max(date_end, na.rm = TRUE)),
    first_requested_at = suppressWarnings(min(first_requested_at, na.rm = TRUE)),
    last_downloaded_at = suppressWarnings(max(last_downloaded_at, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  mutate(
    station_route_download_status = dplyr::case_when(
      n_failed_windows == 0 ~ "completed",
      n_success_windows > 0 ~ "partial",
      TRUE ~ "failed"
    )
  )

station_route_status <- station_route_summary %>%
  select(
    station_code,
    route_name,
    n_windows,
    n_success_windows,
    n_failed_windows,
    n_attempts,
    n_success_attempts,
    n_failed_attempts,
    n_positive_windows,
    total_items_success,
    station_route_download_status
  )

# ============================================================
# Station-level summary and status
# ============================================================

station_summary <- window_status %>%
  group_by(station_code) %>%
  summarise(
    n_routes_logged = dplyr::n_distinct(route_name),
    n_windows = n(),
    n_success_windows = sum(ever_success, na.rm = TRUE),
    n_failed_windows = sum(!ever_success, na.rm = TRUE),
    n_attempts = sum(n_attempts, na.rm = TRUE),
    n_success_attempts = sum(n_success_attempts, na.rm = TRUE),
    n_failed_attempts = sum(n_failed_attempts, na.rm = TRUE),
    n_positive_windows = sum(has_items_any_success, na.rm = TRUE),
    total_items_success = sum(total_items_success, na.rm = TRUE),
    .groups = "drop"
  )

station_status <- station_route_status %>%
  group_by(station_code) %>%
  summarise(
    n_routes_logged = dplyr::n_distinct(route_name),
    n_routes_completed = sum(station_route_download_status == "completed", na.rm = TRUE),
    n_routes_partial = sum(station_route_download_status == "partial", na.rm = TRUE),
    n_routes_failed = sum(station_route_download_status == "failed", na.rm = TRUE),
    n_windows = sum(n_windows, na.rm = TRUE),
    n_success_windows = sum(n_success_windows, na.rm = TRUE),
    n_failed_windows = sum(n_failed_windows, na.rm = TRUE),
    n_attempts = sum(n_attempts, na.rm = TRUE),
    n_success_attempts = sum(n_success_attempts, na.rm = TRUE),
    n_failed_attempts = sum(n_failed_attempts, na.rm = TRUE),
    n_positive_windows = sum(n_positive_windows, na.rm = TRUE),
    total_items_success = sum(total_items_success, na.rm = TRUE),
    station_download_status = dplyr::case_when(
      n_routes_failed == 0 & n_routes_partial == 0 ~ "completed",
      n_routes_completed > 0 | n_routes_partial > 0 ~ "partial",
      TRUE ~ "failed"
    ),
    .groups = "drop"
  )

# ============================================================
# Write outputs
# ============================================================

readr::write_csv(route_summary, route_summary_file)
readr::write_csv(station_summary, station_summary_file)
readr::write_csv(station_route_summary, station_route_summary_file)
readr::write_csv(station_route_status, station_route_download_status_file)
readr::write_csv(station_status, station_download_status_file)

# ============================================================
# Console summary
# ============================================================

cat("\n============================================================\n")
cat("Discharge download summaries updated\n")
cat("============================================================\n")
cat("Request log rows:       ", nrow(request_log), "\n")
cat("Window status rows:     ", nrow(window_status), "\n")
cat("Availability index:     ", availability_index_file, "\n")
cat("Window status:          ", window_status_file, "\n")
cat("Route summary:          ", route_summary_file, "\n")
cat("Station summary:        ", station_summary_file, "\n")
cat("Station-route summary:  ", station_route_summary_file, "\n")
cat("Station-route status:   ", station_route_download_status_file, "\n")
cat("Station status:         ", station_download_status_file, "\n")

cat("\nRoute summary based on window-level ever_success:\n")
print(route_summary)

cat("\nStation-route status counts:\n")
print(
  station_route_status %>%
    count(route_name, station_route_download_status)
)

cat("\nDone.\n")
